# -*- coding: utf-8 -*-
"""data_cleaning_idx_sow.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oF4SZtPAxJ-rCXtifdI11nGWLGIyOldH
"""

#Import statments

import pandas as pd
import plotly as plt
import plotly.express as px
import glob
import os

#Loading all csv files

df1 = pd.read_csv('/content/CRMLSSold202502.csv')
df2 = pd.read_csv('/content/CRMLSSold202503.csv')
df3 = pd.read_csv('/content/CRMLSSold202504.csv')
df4 = pd.read_csv('/content/CRMLSSold202505.csv')
df5 = pd.read_csv('/content/CRMLSSold202506.csv')
df6 = pd.read_csv('/content/CRMLSSold202507.csv')

#Merging all the data frames together

df = pd.merge(df1, df2, how = 'outer')
df = pd.merge(df, df3, how='outer')
df = pd.merge(df, df4, how='outer')
df = pd.merge(df, df5, how = 'outer')
df = pd.merge(df, df6, how = 'outer')

df

cols = ['ClosePrice', 'LivingArea', 'BedroomsTotal', 'BathroomsTotalInteger', 'LotSizeAcres'];
eda_df = df[cols];
eda_df['Group'] = ((df['PropertyType'] == 'Residential') & (df['PropertySubType'] == 'SingleFamilyResidence')).map({True: 'Single Family Residential', False: 'Other'});
print(eda_df);

#Begining the data cleaning

df['Group'] = ((df['PropertyType'] == 'Residential') & (df['PropertySubType'] == 'SingleFamilyResidence')).map({True: 'Single Family Residential', False: 'Other'});

df = df.drop(columns = ['ListPrice', 'OriginalListPrice', 'ListAgentAOR', 'ListingKey', 'ListAgentEmail', 'ListAgentFirstName', 'ListAgentLastName', 'ListOfficeName', 'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName', 'ListingKeyNumeric', 'ListingId'])
print(df.isna().sum())
print(len(df))

#Checking how much of each column is NA values

na_pct = df.isna().mean().sort_values(ascending=False)
na_pct.head(30)

#Dropping the NA values with NA_percents over 90
df = df.drop(columns = ['AboveGradeFinishedArea', 'MiddleOrJuniorSchoolDistrict', 'FireplacesTotal', 'ElementarySchoolDistrict', 'CoveredSpaces', 'TaxYear', 'WaterfrontYN', 'BusinessType', 'TaxAnnualAmount', 'BelowGradeFinishedArea', 'BasementYN', 'BuilderName', 'LotSizeDimensions', 'CoBuyerAgentFirstName' ])

#Fixing some of the present NA values
#Droping the rows where NA values are present in ClosePrice, PropertyType & PropertySubType, as they are some of the most important columns in the dataset
df = df.dropna(subset=['ClosePrice', 'PropertyType', 'PropertySubType'])

df

#Checking the percent of na values in different colums given the previous changes
na_pct = df.isna().mean().sort_values(ascending=False)
na_pct.head(30)

#Changing all string NA values to "unknown"
cat_cols = df.select_dtypes(include=['object', 'category']).columns
df[cat_cols] = df[cat_cols].fillna("Unknown")

na_pct = df.isna().mean().sort_values(ascending=False)
na_pct.head(30)

#Changing all numerical NA values to "0"
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(0)

#Doublechecking the code worked & that no values have any present na values.
na_pct = df.isna().mean().sort_values(ascending=False)
na_pct.head(30)

#Original attempt to download csv
df.to_csv("idx_cleaned_data.csv", index=False)

from google.colab import files
files.download("idx_cleaned_data.csv")

#Splitting csv into three files due to its size, and downloading them for future use
n = len(df)
dfa = df.iloc[:n//3]
dfb = df.iloc[n//3:2*n//3]
dfc = df.iloc[2*n//3:]

dfa.to_csv("idx_cleanded_data1.csv", index = False)
dfb.to_csv("idx_cleanded_data2.csv", index = False)
dfc.to_csv("idx_cleanded_data3.csv", index = False)

files.download("idx_cleanded_data1.csv")
files.download("idx_cleanded_data2.csv")
files.download("idx_cleanded_data3.csv")

files.download("idx_cleaned_data1.csv")

files.download("idx_cleaned_data2.csv")

files.download("idx_cleaned_data3.csv")